# Generated by Django 6.0.6 on 2026-06-28 07:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('provider', models.CharField(max_length=64)),
                ('job_title', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('min_years_experience', models.PositiveIntegerField()),
                ('skills', models.JSONField(default=list)),
                ('optional_filters', models.JSONField(default=dict)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('filtered_out', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('score', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('current_company', models.CharField(max_length=255)),
                ('current_designation', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('matched_skills', models.JSONField(default=list)),
                ('breakdown', models.JSONField(default=dict)),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('source_url', models.URLField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='mapping.searchrun')),
            ],
            options={
                'ordering': ['run', 'rank'],
            },
        ),
    ]
